import { StyleSheet } from 'react-native';
import { colors } from './tokens';

export const DRAWER_WIDTH = 280;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceHover,
  },
  menuButton: {
    padding: 4,
  },
  headerTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 30,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBox: {
    alignItems: 'center',
    paddingVertical: 32,
    gap: 8,
  },
  loadingText: {
    color: colors.textMuted,
    marginTop: 12,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  errorText: {
    color: colors.dangerText,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
  },
  screenContainer: {
    flex: 1,
  },
  balanceCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 16,
  },
  balanceLabel: {
    color: colors.textMuted,
    fontSize: 14,
    marginBottom: 4,
  },
  balanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  balanceMonth: {
    color: colors.textDim,
    fontSize: 12,
    marginBottom: 4,
  },
  balanceValue: {
    fontSize: 40,
    fontWeight: '700',
    marginBottom: 16,
  },
  balanceRow: {
    flexDirection: 'row',
    gap: 32,
  },
  balanceItem: {
    flexDirection: 'column',
  },
  balanceItemLabel: {
    color: colors.textMuted,
    fontSize: 12,
  },
  balanceItemValue: {
    fontSize: 18,
    fontWeight: '600',
  },
  section: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 16,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  emptyText: {
    color: colors.textDim,
    textAlign: 'center',
    padding: 16,
  },
  emptySubtext: {
    color: colors.textDim,
    fontSize: 13,
    textAlign: 'center',
    padding: 4,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  dashboardEmpty: {
    alignItems: 'center',
    paddingVertical: 16,
    gap: 6,
  },
  dashboardEmptyIcon: {
    fontSize: 32,
    marginBottom: 4,
  },
  dashboardEmptyTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  dashboardEmptyDesc: {
    color: colors.textMuted,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 260,
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginTop: 8,
  },
  categoryRow: {
    marginBottom: 12,
  },
  categoryLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  categoryName: {
    color: colors.text,
    fontSize: 14,
  },
  categoryTotal: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '500',
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.surfaceHover,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  searchIcon: {
    fontSize: 14,
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    paddingVertical: 10,
  },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  pageTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  addButtonText: {
    color: colors.bg,
    fontWeight: '600',
    fontSize: 14,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 8,
  },
  transactionLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  categoryIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryIconText: {
    fontSize: 16,
  },
  transactionInfo: {
    flex: 1,
  },
  transactionDescriptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  installmentTag: {
    backgroundColor: colors.warningBg,
    borderWidth: 1,
    borderColor: colors.warningBorder,
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  installmentTagText: {
    color: colors.warningText,
    fontSize: 9,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  transactionDescription: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
    flexShrink: 1,
  },
  transactionMeta: {
    color: colors.textDim,
    fontSize: 12,
    marginTop: 2,
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: '600',
  },
  transactionActions: {
    flexDirection: 'row',
    gap: 4,
  },
  editButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  editButtonText: {
    color: colors.textMuted,
    fontSize: 12,
  },
  deleteButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
  },
  deleteButtonText: {
    color: colors.danger,
    fontSize: 12,
  },
  separator: {
    height: 1,
    backgroundColor: colors.surface,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginTop: 8,
  },
  formTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  label: {
    color: colors.textMuted,
    fontSize: 14,
    marginBottom: 4,
    marginTop: 12,
  },
  input: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    padding: 12,
    color: colors.text,
    fontSize: 16,
  },
  autoFillHint: {
    color: colors.primary,
    fontSize: 12,
    marginTop: 8,
  },
  dateButton: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  dateButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  datePickerOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  datePickerModal: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 24,
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceHover,
  },
  datePickerTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  datePickerCancel: {
    color: colors.textMuted,
    fontSize: 15,
  },
  datePickerDone: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  typeToggle: {
    flexDirection: 'row',
    gap: 8,
  },
  typeButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    alignItems: 'center',
  },
  typeButtonActive: {
    backgroundColor: colors.surfaceHover,
    borderColor: colors.borderStrong,
  },
  typeButtonText: {
    color: colors.textMuted,
    fontWeight: '500',
  },
  typeButtonTextActive: {
    color: colors.text,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.bg,
  },
  categoryChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  categoryChipText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  categoryChipTextActive: {
    color: colors.text,
  },
  submitButton: {
    backgroundColor: colors.primary,
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 24,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: colors.bg,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  cancelButtonText: {
    color: colors.textMuted,
    fontSize: 16,
  },
  // --- Quick Add widget ---
  quickAddCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 16,
  },
  quickAddHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  quickAddTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  quickAddToday: {
    alignItems: 'flex-end',
  },
  quickAddTodayLabel: {
    color: colors.textMuted,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  quickAddTodayValue: {
    color: colors.expense,
    fontSize: 16,
    fontWeight: '700',
  },
  quickAddRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  quickAddAmount: {
    width: 110,
    fontSize: 16,
  },
  quickAddDescription: {
    flex: 1,
    fontSize: 16,
  },
  quickAddError: {
    color: colors.dangerText,
    fontSize: 13,
    marginTop: 8,
  },
  quickAddButton: {
    backgroundColor: colors.expense,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  quickAddButtonIncome: {
    backgroundColor: colors.income,
  },
  quickAddButtonText: {
    color: colors.bg,
    fontSize: 15,
    fontWeight: '700',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  drawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: DRAWER_WIDTH,
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.surfaceHover,
    paddingTop: 48,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceHover,
  },
  drawerTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  drawerClose: {
    padding: 4,
  },
  drawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  drawerItemActive: {
    backgroundColor: colors.surfaceHover,
  },
  drawerItemText: {
    color: colors.textMuted,
    fontSize: 16,
  },
  drawerItemTextActive: {
    color: colors.text,
    fontWeight: '600',
  },
  drawerDivider: {
    height: 1,
    backgroundColor: colors.surfaceHover,
    marginHorizontal: 20,
    marginVertical: 8,
  },
  drawerSectionLabel: {
    color: colors.textDim,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 2,
  },
  drawerFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: colors.surfaceHover,
    paddingTop: 8,
  },
  drawerUser: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  drawerUserEmail: {
    color: colors.textDim,
    fontSize: 12,
  },
  drawerLangRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  drawerLangLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 16,
  },
  navButton: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonText: {
    color: colors.textMuted,
    fontSize: 18,
  },
  monthLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
    minWidth: 140,
    textAlign: 'center',
  },
  overviewCards: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  overviewCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  overviewLabel: {
    color: colors.textMuted,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  overviewValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  budgetCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 12,
  },
  budgetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  budgetCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  budgetCategoryName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  warningBadge: {
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  budgetItemActions: {
    flexDirection: 'row',
    gap: 4,
  },
  budgetMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 4,
  },
  budgetMetaText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  budgetPctText: {
    fontSize: 13,
    fontWeight: '600',
  },
  remainingText: {
    color: colors.primary,
    fontSize: 13,
  },
  overText: {
    color: colors.danger,
    fontSize: 13,
  },
  alertSection: {
    backgroundColor: colors.warningBg,
    borderWidth: 1,
    borderColor: colors.warningBorder,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    gap: 8,
  },
  alertTitle: {
    color: colors.warningText,
    fontSize: 14,
    fontWeight: '700',
  },
  alertCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    padding: 10,
  },
  alertInfo: {
    flex: 1,
    gap: 2,
  },
  alertCategory: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  alertText: {
    fontSize: 12,
  },
  ackButton: {
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ackButtonText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  groupTitle: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  categoryCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    width: 100,
  },
  categoryCardName: {
    color: colors.text,
    fontSize: 13,
    textAlign: 'center',
  },
  // --- Category management list (CategoriesScreen) ---
  categorySearch: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 14,
    marginBottom: 12,
  },
  categoryTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  categoryTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surface,
  },
  categoryTabActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  categoryTabText: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  categoryTabTextActive: {
    color: colors.text,
    fontWeight: '700',
  },
  categoryList: {
    gap: 8,
  },
  categoryListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  categoryRowInfo: {
    flex: 1,
  },
  categoryListTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  categoryCardSub: {
    color: colors.textDim,
    fontSize: 12,
    marginTop: 2,
  },
  categoryMore: {
    color: colors.textDim,
    fontSize: 18,
    paddingHorizontal: 4,
  },
  // --- Accounts (AccountsScreen) ---
  accountSearch: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 14,
    marginBottom: 14,
  },
  accountGroup: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 14,
  },
  accountGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  accountGroupIcon: {
    fontSize: 18,
  },
  accountGroupHeaderText: {
    flex: 1,
  },
  accountGroupTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  accountGroupBlurb: {
    color: colors.textDim,
    fontSize: 11,
    marginTop: 1,
  },
  accountGroupBadge: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
    backgroundColor: colors.bg,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    overflow: 'hidden',
  },
  accountGroupEmpty: {
    color: colors.textDim,
    fontSize: 13,
    paddingVertical: 6,
  },
  accountList: {
    gap: 8,
  },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.bg,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  accountIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountIconDebt: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  accountIconText: {
    fontSize: 16,
  },
  accountRowInfo: {
    flex: 1,
  },
  accountRowName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  accountRowMeta: {
    color: colors.textDim,
    fontSize: 11,
    marginTop: 2,
  },
  accountBalance: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  accountBalanceDebt: {
    color: colors.dangerText,
    fontSize: 14,
    fontWeight: '600',
  },
  accountTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  accountTypeButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.bg,
  },
  accountTypeButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  accountTypeButtonText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  accountTypeButtonTextActive: {
    color: colors.text,
  },
  accountCardFields: {
    marginTop: 12,
    backgroundColor: colors.surfaceHover,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  accountCardFieldsHint: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 16,
  },
  accountCardFieldsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  accountCardField: {
    flex: 1,
  },
  // --- Credit cards (CreditCardsScreen) ---
  creditCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    padding: 12,
    marginBottom: 8,
  },
  creditCardActive: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  creditCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  creditCardName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    flexShrink: 1,
  },
  creditCardBadgeOpen: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  creditCardBadgePaid: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  creditCardBalance: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
    marginVertical: 6,
  },
  creditCardMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  creditCardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  creditCardCurrentBill: {
    backgroundColor: colors.surfaceHover,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  creditCardCurrentBillLabel: {
    color: colors.textMuted,
    fontSize: 12,
  },
  creditCardCurrentBillValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
    marginVertical: 2,
  },
  creditCardCurrentBillMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  creditCardBillRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface,
    gap: 8,
  },
  creditCardBillRowText: {
    color: colors.textMuted,
    fontSize: 12,
    flexShrink: 1,
  },
  creditCardBillPaid: {
    color: colors.success,
    fontSize: 12,
    fontWeight: '600',
  },
  creditCardBillOpen: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.primaryText,
    fontSize: 14,
    fontWeight: '600',
  },
  pickerWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.bg,
  },
  pillActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  pillText: {
    color: colors.textMuted,
    fontSize: 12,
  },
  pillTextActive: {
    color: colors.text,
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // --- Settings rows (NotificationSettingsScreen) ---
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface,
  },
  settingRowText: {
    flex: 1,
  },
  settingRowTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  settingRowDesc: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.surfaceHover,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxCheck: {
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: '700',
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.surfaceHover,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary,
  },
  // --- Receipts (ReceiptsScreen) ---
  receiptHint: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 14,
  },
  receiptQrInput: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    padding: 12,
    color: colors.text,
    fontSize: 13,
    fontFamily: 'monospace',
    minHeight: 90,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  receiptFields: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 14,
  },
  receiptField: {
    minWidth: '40%',
  },
  receiptFieldLabel: {
    color: colors.textDim,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  receiptFieldValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  receiptItemReview: {
    marginBottom: 14,
    gap: 8,
  },
  receiptItemTitle: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  receiptItemRow: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  receiptItemInput: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    color: colors.text,
    fontSize: 13,
  },
  receiptItemDesc: {
    flex: 2,
  },
  receiptItemSmall: {
    flex: 1,
    minWidth: 56,
  },
  receiptItemRemove: {
    padding: 4,
  },
  receiptItemRemoveText: {
    color: colors.danger,
    fontSize: 14,
  },
  receiptItemAdd: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  receiptItemAddText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  receiptList: {
    gap: 8,
  },
  receiptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.bg,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  receiptRowInfo: {
    flex: 1,
  },
  receiptRowStore: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  receiptRowDate: {
    color: colors.textDim,
    fontSize: 12,
    marginTop: 2,
  },
  receiptRowTotal: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  // --- Audit (AuditScreen) ---
  auditFilters: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  auditFilterInput: {
    flex: 1,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 13,
  },
  auditList: {
    gap: 8,
  },
  auditRow: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  auditRowHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  auditRowLeft: {
    flex: 1,
  },
  auditEventType: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  auditAggregate: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  auditTime: {
    color: colors.textDim,
    fontSize: 11,
  },
  auditPayload: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: 'monospace',
    marginTop: 10,
    backgroundColor: colors.bg,
    borderRadius: 8,
    padding: 10,
  },
  // --- Ledger (LedgerScreen) ---
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  ledgerHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ledgerList: {
    gap: 10,
  },
  ledgerCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  ledgerCardHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 8,
  },
  ledgerCardDescription: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  ledgerCardDate: {
    color: colors.textDim,
    fontSize: 12,
  },
  ledgerEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.bg,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginTop: 4,
  },
  ledgerEntryAccount: {
    color: colors.text,
    fontSize: 13,
  },
  ledgerEntryDebit: {
    color: colors.dangerText,
    fontSize: 13,
    fontWeight: '600',
  },
  ledgerEntryCredit: {
    color: colors.income,
    fontSize: 13,
    fontWeight: '600',
  },
  ledgerAccountPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  ledgerAccountChip: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: '48%',
  },
  ledgerAccountChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  ledgerAccountChipText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  ledgerAccountChipTextActive: {
    color: colors.text,
  },
  // --- Server (ServerScreen) ---
  serverCurrent: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'monospace',
    backgroundColor: colors.bg,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
  },
  trendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  trendLabel: {
    color: colors.textMuted,
    fontSize: 12,
    width: 44,
  },
  trendValues: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
    flex: 1,
  },
  trendIncomeText: {
    color: colors.primary,
    fontSize: 11,
  },
  trendExpenseText: {
    color: colors.danger,
    fontSize: 11,
  },
  chartArea: {
    alignItems: 'center',
    marginBottom: 16,
  },
  donutLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.bg,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 0,
  },
  legendSwatch: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendLabel: {
    color: colors.textMuted,
    fontSize: 12,
    flexShrink: 1,
    maxWidth: 140,
  },
  legendValue: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  readOnlyField: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    padding: 12,
  },
  readOnlyText: {
    color: colors.text,
    fontSize: 16,
  },
  reconHint: {
    color: colors.textDim,
    fontSize: 13,
    marginBottom: 4,
  },
  reconCsvInput: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    padding: 12,
    color: colors.text,
    fontSize: 13,
    fontFamily: 'monospace',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  reconErrorBox: {
    backgroundColor: colors.dangerBg,
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  reconErrorText: {
    color: colors.dangerText,
    fontSize: 13,
  },
  reconSummaryRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  reconSummaryItem: {
    flex: 1,
    backgroundColor: colors.bg,
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
  },
  reconSummaryLabel: {
    color: colors.textMuted,
    fontSize: 11,
    marginBottom: 4,
  },
  reconSummaryValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  reconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface,
    gap: 8,
  },
  reconRowLeft: {
    flex: 1,
  },
  reconDate: {
    color: colors.textDim,
    fontSize: 11,
  },
  reconDescription: {
    color: colors.text,
    fontSize: 13,
    marginTop: 2,
  },
  reconRowRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  reconAmount: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
  },
  reconStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  reconStatusText: {
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    maxHeight: '90%',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 16,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  iconButton: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  iconButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryHover,
  },
  iconButtonText: {
    color: colors.textMuted,
    fontSize: 12,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  colorButton: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorButtonActive: {
    borderColor: colors.text,
  },
  monthPreview: {
    color: colors.textMuted,
    fontSize: 14,
    marginTop: 12,
  },
  // --- Installments screen ---
  planCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    marginBottom: 12,
  },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 12,
  },
  planCategory: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  categoryIconEmoji: {
    fontSize: 18,
  },
  planTitleBlock: {
    flex: 1,
  },
  planTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  planSubtitle: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  planAmounts: {
    alignItems: 'flex-end',
  },
  planTotal: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  planRemaining: {
    color: colors.textMuted,
    fontSize: 12,
  },
  planActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  planActionButton: {
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  planActionButtonText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  planDeleteButton: {
    borderColor: colors.dangerBorder,
  },
  planDeleteText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '600',
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  modalClose: {
    color: colors.textMuted,
    fontSize: 16,
    padding: 4,
  },
  planDetailMeta: {
    color: colors.textMuted,
    fontSize: 13,
    marginBottom: 12,
  },
  installmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    borderRadius: 10,
    marginBottom: 6,
  },
  installmentNumber: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
    minWidth: 36,
  },
  installmentDue: {
    color: colors.textMuted,
    fontSize: 12,
    flex: 1,
  },
  installmentStatus: {
    color: colors.text,
    fontSize: 12,
    flex: 1,
  },
  payButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  payButtonText: {
    color: colors.primaryText,
    fontSize: 12,
    fontWeight: '700',
  },
});
