/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists audit events with optional filters (admin-only). */
        get: operations["list_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logs a user in and returns tokens. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns current user info from Bearer token. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refreshes tokens. */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registers a new user. */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists budgets for a given month/year, joined with category display info. */
        get: operations["list_budgets"];
        put?: never;
        /** Creates or updates a budget (upsert on (category_id, month, year)). */
        post: operations["create_budget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns budget vs actual spending for a given month/year. */
        get: operations["budget_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes a budget by ID. */
        delete: operations["delete_budget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists categories, optionally filtered by type.
         * @description Returns `400` if an invalid `type` filter is provided.
         */
        get: operations["list_categories"];
        put?: never;
        /**
         * Creates a new category.
         * @description Returns `400` if the payload is invalid (missing name, invalid type,
         *     non-existent parent category).
         */
        post: operations["create_category"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all accounts in the chart of accounts. */
        get: operations["list_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists ledger transactions (grouped by transaction_id) with their entries. */
        get: operations["list_ledger_transactions"];
        put?: never;
        /** Creates a new double-entry ledger transaction. */
        post: operations["create_ledger_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrate/single-to-double": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrates all simple transactions to double-entry ledger pairs. */
        post: operations["migrate_single_to_double"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists saved receipts (paginated). */
        get: operations["list_receipts"];
        put?: never;
        /** Saves a reviewed receipt (and upserts its store), creating normalized products. */
        post: operations["save_receipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns price history for a normalized product. */
        get: operations["price_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/product/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merges two normalized products (all items reassigned to target; source deleted). */
        post: operations["merge_products"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scans a raw NFC-e QR code and returns the parsed receipt preview. */
        post: operations["scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconciles uploaded statement lines against existing transactions. */
        post: operations["reconcile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/category-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category spending breakdown for a date range. */
        get: operations["category_breakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly income/expense summary over a date range. */
        get: operations["monthly_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly trends (income, expense, net) over the last N months. */
        get: operations["trends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns income, expense, and balance totals for a given month,
         *     with a per-category breakdown.
         */
        get: operations["get_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists transactions, with optional filters (category, type, date range) and pagination. */
        get: operations["list_transactions"];
        put?: never;
        /** Creates a new transaction. */
        post: operations["create_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a single transaction by ID. */
        get: operations["get_transaction"];
        /** Updates an existing transaction. */
        put: operations["update_transaction"];
        post?: never;
        /** Deletes a transaction by ID. */
        delete: operations["delete_transaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns the health status of the backend and its dependencies
         *     (PostgreSQL, RabbitMQ). Returns 200 if healthy, 503 if degraded.
         */
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exposes Prometheus-formatted metrics for scraping.
         *     This endpoint is served on a separate port in production (default 3001).
         */
        get: operations["metrics_handler_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A chart-of-accounts account. */
        Account: {
            /**
             * Format: date-time
             * @description Row creation timestamp.
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Unique account identifier.
             */
            id: string;
            /** @description Account display name (e.g., "Cash"). */
            name: string;
            /**
             * Format: uuid
             * @description Optional parent account.
             */
            parent_id?: string | null;
            /** @description `asset`, `liability`, `equity`, `income`, or `expense`. */
            type: string;
        };
        /** @description A monthly budget limit for a category. */
        Budget: {
            /** @description Maximum spend limit for the month. */
            amount_limit: string;
            /**
             * Format: uuid
             * @description Category this budget applies to.
             */
            category_id: string;
            /**
             * Format: date-time
             * @description Row creation timestamp.
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Unique budget identifier.
             */
            id: string;
            /**
             * Format: int32
             * @description Month (1-12).
             */
            month: number;
            /**
             * Format: date-time
             * @description Last row update timestamp.
             */
            updated_at: string;
            /**
             * Format: int32
             * @description Year.
             */
            year: number;
        };
        /** @description Response for a paginated/period budget list. */
        BudgetListResponse: {
            /** @description Budgets for the selected period. */
            items: components["schemas"]["BudgetWithCategory"][];
            /**
             * Format: int32
             * @description Month used for the query.
             */
            month: number;
            /**
             * Format: int32
             * @description Year used for the query.
             */
            year: number;
        };
        /** @description Budget vs actual spending for a single budget. */
        BudgetSummaryItem: {
            /** @description Actual spending for the category in the month (from transactions). */
            actual_spent: string;
            /** @description The budget itself (with category info). */
            budget: components["schemas"]["BudgetWithCategory"];
            /** @description Percentage of the limit used (0-100+, can exceed 100). */
            percentage: string;
            /** @description Remaining amount = condition. negative => over budget. */
            remaining: string;
        };
        /** @description Response for the budget summary endpoint. */
        BudgetSummaryResponse: {
            /** @description Per-budget spend vs limit. */
            items: components["schemas"]["BudgetSummaryItem"][];
            /**
             * Format: int32
             * @description Month used for the query.
             */
            month: number;
            /** @description Sum of all budget limits for the period. */
            total_budgeted: string;
            /** @description Sum of all actual spending for budgeted categories. */
            total_spent: string;
            /**
             * Format: int32
             * @description Year used for the query.
             */
            year: number;
        };
        /** @description Budget joined with its category display info. */
        BudgetWithCategory: {
            /** @description Maximum spend limit for the month. */
            amount_limit: string;
            /**
             * Format: uuid
             * @description Category id this budget applies to.
             */
            category_id: string;
            /** @description Category name. */
            category_name: string;
            /** @description Category hex color. */
            color?: string | null;
            /** @description Category icon identifier. */
            icon?: string | null;
            /**
             * Format: uuid
             * @description Unique budget identifier.
             */
            id: string;
            /**
             * Format: int32
             * @description Month (1-12).
             */
            month: number;
            /**
             * Format: int32
             * @description Year.
             */
            year: number;
        };
        /** @description A transaction category (income or expense), optionally nested via `parent_id`. */
        Category: {
            /** @description Hex color code (e.g., `#ef4444`). */
            color?: string | null;
            /**
             * Format: date-time
             * @description Row creation timestamp.
             */
            created_at: string;
            /** @description Icon identifier used by the web/mobile UIs. */
            icon?: string | null;
            /**
             * Format: uuid
             * @description Unique category identifier.
             */
            id: string;
            /** @description Display name (e.g., "Food & Groceries"). */
            name: string;
            /**
             * Format: uuid
             * @description Optional parent category for subcategories.
             */
            parent_id?: string | null;
            /** @description `income` or `expense`. */
            type: string;
            /**
             * Format: date-time
             * @description Last row update timestamp.
             */
            updated_at: string;
        };
        /** @description A single category's aggregated totals for the category-breakdown report. */
        CategoryBreakdownItem: {
            /**
             * Format: uuid
             * @description Category UUID (null when uncategorised).
             */
            category_id?: string | null;
            /** @description Category name. */
            category_name?: string | null;
            /** @description Hex color. */
            color?: string | null;
            /** @description Icon identifier. */
            icon?: string | null;
            /** @description Percentage of all expenses for the period. */
            percentage: string;
            /** @description Total amount for the category. */
            total: string;
            /**
             * Format: int64
             * @description Number of transactions in this category.
             */
            transaction_count: number;
        };
        /** @description Response for the category-breakdown report. */
        CategoryBreakdownResponse: {
            /** @description Per-category totals, sorted by total descending. */
            categories: components["schemas"]["CategoryBreakdownItem"][];
            /**
             * Format: date
             * @description Date range used (ISO dates).
             */
            end_date: string;
            /**
             * Format: date
             * @description Date range used (ISO dates).
             */
            start_date: string;
        };
        /** @description Query parameters for filtering the category list. */
        CategoryListParams: {
            /** @description Filter by `income` or `expense`. */
            type?: string | null;
        };
        /** @description Per-category totals for the summary endpoint. */
        CategorySummary: {
            /**
             * Format: uuid
             * @description Category UUID (null for transactions without a category).
             */
            category_id?: string | null;
            /** @description Category display name. */
            category_name?: string | null;
            /** @description Hex color code for the category. */
            color?: string | null;
            /** @description Icon identifier for the category. */
            icon?: string | null;
            /** @description Total amount for this category. */
            total: string;
        };
        /** @description Payload for creating or updating a budget (upsert). */
        CreateBudgetRequest: {
            /**
             * @description Maximum spend limit — must be > 0.
             * @example 500.00
             */
            amount_limit: string;
            /**
             * Format: uuid
             * @description Category this budget applies to (expense categories only).
             */
            category_id: string;
            /**
             * Format: int32
             * @description Month (1-12).
             */
            month: number;
            /**
             * Format: int32
             * @description Year.
             */
            year: number;
        };
        /** @description Payload for creating a new category. */
        CreateCategoryRequest: {
            /** @description Hex color code (e.g., `#ef4444`). */
            color?: string | null;
            /** @description Icon identifier used by the web/mobile UIs. */
            icon?: string | null;
            /** @description Display name (e.g., "Food & Groceries"). */
            name: string;
            /**
             * Format: uuid
             * @description Optional parent category for subcategories.
             */
            parent_id?: string | null;
            /**
             * @description `income` or `expense`.
             * @example expense
             */
            type: string;
        };
        /** @description Payload for creating a ledger transaction (double-entry). */
        CreateLedgerTransactionRequest: {
            /**
             * Format: date
             * @description Calendar date of the transaction.
             * @example 2026-08-06
             */
            date: string;
            /** @description Human-readable description (e.g., "Groceries at Supermarket X"). */
            description: string;
            /** @description At least two entries; debits must equal credits. */
            entries: components["schemas"]["LedgerEntryRequest"][];
            /** @description Optional idempotency key (unique per client request). */
            idempotency_key?: string | null;
        };
        /** @description Response for creating a ledger transaction. */
        CreateLedgerTransactionResponse: {
            /**
             * Format: int32
             * @description HTTP status to return (201 or 200 for idempotent replay).
             */
            status: number;
            /** @description The created ledger transaction. */
            transaction: components["schemas"]["LedgerTransaction"];
        };
        /** @description Payload for creating a new transaction. */
        CreateTransactionRequest: {
            /**
             * @description Monetary amount — must be > 0.
             * @example 150.00
             */
            amount: string;
            /**
             * Format: uuid
             * @description Category this transaction belongs to.
             */
            category_id?: string | null;
            /**
             * Format: date
             * @description Calendar date of the transaction (ISO 8601 `YYYY-MM-DD`).
             * @example 2026-04-08
             */
            date: string;
            /** @description Human-readable description (e.g., "Lunch at Restaurante X"). */
            description: string;
            /** @description Optional free-form notes. */
            notes?: string | null;
            /**
             * @description `income` or `expense`.
             * @example expense
             */
            type: string;
        };
        /** @description Failed health check payload returned with HTTP 503. */
        HealthError: {
            /** @description Database connection state (e.g., `"disconnected"`). */
            database: string;
            /** @description Human-readable explanation of the failure. */
            details: string;
            /** @description RabbitMQ connection state (e.g., `"unknown"`). */
            rabbitmq: string;
            /** @description Overall service status (e.g., `"unhealthy"`). */
            status: string;
        };
        /** @description Successful health check payload returned with HTTP 200. */
        HealthResponse: {
            /** @description Database connection state (e.g., `"connected"`). */
            database: string;
            /** @description RabbitMQ connection state (e.g., `"disabled"`). */
            rabbitmq: string;
            /** @description Overall service status (e.g., `"ok"`). */
            status: string;
            /** @description Backend crate version from `CARGO_PKG_VERSION`. */
            version: string;
        };
        /** @description A single ledger entry. */
        LedgerEntry: {
            /**
             * Format: uuid
             * @description Account ID this entry posts to.
             */
            account_id: string;
            /** @description Account display name (nullable, populated on list queries). */
            account_name?: string | null;
            /** @description Credit amount (always >= 0). */
            credit_amount: string;
            /** @description Debit amount (always >= 0). */
            debit_amount: string;
            /** @description Optional description. */
            description?: string | null;
            /**
             * Format: uuid
             * @description Unique entry identifier.
             */
            id: string;
            /**
             * Format: date-time
             * @description Recorded timestamp.
             */
            recorded_at: string;
            /**
             * Format: uuid
             * @description Transaction ID this entry belongs to.
             */
            transaction_id: string;
        };
        /** @description A single debit/credit entry in a ledger transaction. */
        LedgerEntryRequest: {
            /**
             * Format: uuid
             * @description Account this entry posts to.
             */
            account_id: string;
            /**
             * @description Credit amount (positive; must be zero on debit entries).
             * @example 0.00
             */
            credit_amount: string;
            /**
             * @description Debit amount (positive; must be zero on credit entries).
             * @example 150.00
             */
            debit_amount: string;
            /** @description Optional per-entry description. */
            description?: string | null;
        };
        /** @description A full ledger transaction with its entries. */
        LedgerTransaction: {
            /**
             * Format: date
             * @description Calendar date.
             */
            date: string;
            /** @description Human-readable description. */
            description: string;
            /** @description All ledger entries (must balance: debits = credits). */
            entries: components["schemas"]["LedgerEntry"][];
            /**
             * Format: date-time
             * @description Recorded timestamp.
             */
            recorded_at: string;
            /**
             * Format: uuid
             * @description Unique transaction ID linking all entries.
             */
            transaction_id: string;
        };
        /** @description Request body for logging in. */
        LoginRequest: {
            /** @description User email. */
            email: string;
            /** @description Plaintext password. */
            password: string;
        };
        /** @description Request: merge two normalized products. */
        MergeProductsRequest: {
            /**
             * Format: uuid
             * @description Product to merge into target (will be deleted).
             */
            source_id: string;
            /**
             * Format: uuid
             * @description Product to keep.
             */
            target_id: string;
        };
        /** @description Response for the migration endpoint. */
        MigrationResponse: {
            /**
             * Format: int64
             * @description Number already migrated (skipped).
             */
            already_migrated: number;
            /**
             * Format: int64
             * @description Number that failed during migration.
             */
            failed: number;
            /**
             * Format: int64
             * @description Number successfully migrated to double-entry.
             */
            migrated: number;
            /**
             * Format: int64
             * @description Number of simple transactions examined.
             */
            total_processed: number;
        };
        /** @description A single month's income/expense totals for the monthly report. */
        MonthlyReportItem: {
            /** @description Balance = income − expense. */
            balance: string;
            /** @description Total expenses for the month. */
            expense_total: string;
            /** @description Total income for the month. */
            income_total: string;
            /**
             * Format: int32
             * @description Month (1-12).
             */
            month: number;
            /**
             * Format: int32
             * @description Year.
             */
            year: number;
        };
        /** @description Response for the monthly report. */
        MonthlyReportResponse: {
            /** @description One entry per month in the requested range (chronological order). */
            months: components["schemas"]["MonthlyReportItem"][];
        };
        /** @description Query params for price history. */
        PriceHistoryParams: {
            /**
             * Format: int32
             * @description Months of history (default 6).
             */
            months?: number | null;
            /**
             * Format: uuid
             * @description Normalized product ID.
             */
            product_id: string;
        };
        /** @description Line item for saving a receipt. */
        ReceiptItemInput: {
            /** @description Item description (also becomes a normalized product). */
            description: string;
            /** @description Quantity purchased (default 1). */
            quantity?: string | null;
            /** @description Total price for the line. */
            total_price?: string | null;
            /** @description Unit price. */
            unit_price?: string | null;
        };
        /** @description A reconciliation item result (matched or unmatched). */
        ReconciliationItem: {
            /** @description Match confidence (0-100). */
            confidence?: string | null;
            /**
             * Format: uuid
             * @description Unique item identifier.
             */
            id: string;
            /** @description `matched` or `unmatched`. */
            match_status: string;
            /**
             * Format: uuid
             * @description Transaction ID if matched, otherwise NULL.
             */
            matched_transaction_id?: string | null;
            /**
             * Format: uuid
             * @description Reconciliation ID this item belongs to.
             */
            reconciliation_id: string;
            /** @description Signed statement amount. */
            statement_amount: string;
            /**
             * Format: date
             * @description Statement date.
             */
            statement_date: string;
            /** @description Statement description. */
            statement_description: string;
        };
        /** @description Payload containing all CSV statement lines for reconciliation. */
        ReconciliationUploadRequest: {
            /** @description Statement lines parsed from the uploaded CSV. */
            lines: components["schemas"]["StatementLine"][];
            /** @description Name to identify this statement/reconciliation. */
            statement_name: string;
        };
        /** @description Response from a reconciliation upload. */
        ReconciliationUploadResponse: {
            /** @description Per-row match results. */
            items: components["schemas"]["ReconciliationItem"][];
            /**
             * Format: int64
             * @description Rows matched to existing transactions.
             */
            matched_rows: number;
            /**
             * Format: uuid
             * @description The reconciliation summary.
             */
            reconciliation_id: string;
            /**
             * Format: int64
             * @description Total statement rows processed.
             */
            total_rows: number;
            /**
             * Format: int64
             * @description Rows that don't match any existing transaction.
             */
            unmatched_rows: number;
        };
        /** @description Request body for refreshing an access token. */
        RefreshRequest: {
            /** @description Refresh token issued at login. */
            refresh_token: string;
        };
        /** @description Request body for registering a new user. */
        RegisterRequest: {
            /** @description Optional display name. */
            display_name?: string | null;
            /** @description User email (must be unique). */
            email: string;
            /** @description Plaintext password (hashed with Argon2id). */
            password: string;
        };
        /** @description Request: save a fully parsed/reviewed receipt. */
        SaveReceiptRequest: {
            /** @description Store CNPJ (optional). */
            cnpj?: string | null;
            /**
             * Format: date
             * @description Receipt date.
             */
            date: string;
            /** @description Line items (at least one). */
            items: components["schemas"]["ReceiptItemInput"][];
            /** @description Store name (or from scan). */
            store_name: string;
            /** @description Total amount. */
            total: string;
        };
        /** @description Request: scan a raw NFC-e QR code. */
        ScanRequest: {
            /** @description Raw QR code content (URL or `p=` payload). */
            qr_data: string;
        };
        /** @description A single line item from an uploaded bank statement. */
        StatementLine: {
            /** @description Signed amount (negative for expense/debit, positive for income/credit). */
            amount: string;
            /**
             * Format: date
             * @description Transaction date (ISO `YYYY-MM-DD`).
             */
            date: string;
            /** @description Description from the bank statement. */
            description: string;
        };
        /** @description Query parameters for the summary endpoint. */
        SummaryParams: {
            /**
             * Format: int32
             * @description Month to summarise, 1-12 (defaults to current month).
             */
            month?: number | null;
            /**
             * Format: int32
             * @description Year to summarise (defaults to current year).
             */
            year?: number | null;
        };
        /** @description Monthly summary response: income, expense, balance, and category breakdown. */
        SummaryResponse: {
            /** @description Balance = income − expense. */
            balance: string;
            /** @description Per-category breakdown for the month. */
            by_category: components["schemas"]["CategorySummary"][];
            /** @description Total expenses for the selected month (positive value). */
            expense_total: string;
            /** @description Total income for the selected month (positive value). */
            income_total: string;
            /**
             * Format: int32
             * @description Month used for the query (1-12).
             */
            month: number;
            /**
             * Format: int32
             * @description Year used for the query.
             */
            year: number;
        };
        /** @description A single income or expense transaction. */
        Transaction: {
            /** @description Monetary amount — always positive; `type` determines direction. */
            amount: string;
            /**
             * Format: uuid
             * @description Category this transaction belongs to (nullable if category deleted).
             */
            category_id?: string | null;
            /**
             * Format: date-time
             * @description Row creation timestamp.
             */
            created_at: string;
            /**
             * Format: date
             * @description Calendar date of the transaction.
             */
            date: string;
            /** @description Human-readable description (e.g., "Lunch at Restaurante X"). */
            description: string;
            /**
             * Format: uuid
             * @description Unique transaction identifier.
             */
            id: string;
            /** @description Optional free-form notes. */
            notes?: string | null;
            /** @description `income` or `expense`. */
            type: string;
            /**
             * Format: date-time
             * @description Last row update timestamp.
             */
            updated_at: string;
        };
        /** @description Query parameters for listing transactions. */
        TransactionListParams: {
            /**
             * Format: uuid
             * @description Filter by category UUID.
             */
            category_id?: string | null;
            /**
             * Format: date
             * @description Filter by end date (inclusive, ISO `YYYY-MM-DD`).
             */
            end_date: string;
            /**
             * Format: int32
             * @description Page offset (0-based).
             * @default 0
             */
            page: number;
            /**
             * Format: int32
             * @description Maximum number of rows to return (default 50, max 200).
             * @default 50
             */
            page_size: number;
            /**
             * Format: date
             * @description Filter by start date (inclusive, ISO `YYYY-MM-DD`).
             */
            start_date: string;
            /** @description Filter by `income` or `expense`. */
            type?: string | null;
        };
        /** @description Response wrapper for paginated transaction lists. */
        TransactionListResponse: {
            /** @description Returned items for this page. */
            items: components["schemas"]["Transaction"][];
            /**
             * Format: int32
             * @description Current page offset.
             */
            page: number;
            /**
             * Format: int32
             * @description Page size used for this request.
             */
            page_size: number;
            /**
             * Format: int64
             * @description Total row count matching the filters (regardless of pagination).
             */
            total: number;
        };
        /** @description A single point in the trends report. */
        TrendPoint: {
            /** @description Expenses for the month. */
            expense_total: string;
            /** @description Income for the month. */
            income_total: string;
            /**
             * Format: int32
             * @description Month (1-12).
             */
            month: number;
            /** @description Human-friendly label (e.g., "2026-04"). */
            month_label: string;
            /** @description Net (income − expense) for the month. */
            net: string;
            /**
             * Format: int32
             * @description Year.
             */
            year: number;
        };
        /** @description Response for the trends report. */
        TrendsResponse: {
            /** @description Monthly points, chronological order. */
            trends: components["schemas"]["TrendPoint"][];
        };
        /** @description Payload for updating an existing transaction. */
        UpdateTransactionRequest: {
            /**
             * @description Monetary amount — must be > 0.
             * @example 150.00
             */
            amount: string;
            /**
             * Format: uuid
             * @description Category this transaction belongs to.
             */
            category_id?: string | null;
            /**
             * Format: date
             * @description Calendar date of the transaction (ISO 8601 `YYYY-MM-DD`).
             * @example 2026-04-08
             */
            date: string;
            /** @description Human-readable description (e.g., "Lunch at Restaurante X"). */
            description: string;
            /** @description Optional free-form notes. */
            notes?: string | null;
            /**
             * @description `income` or `expense`.
             * @example expense
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid registration payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_budgets: {
        parameters: {
            query?: {
                /** @description Year (default: current) */
                year?: number;
                /** @description Month 1-12 (default: current) */
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of budgets for the period */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetListResponse"];
                };
            };
            /** @description Invalid month parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_budget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetWithCategory"];
                };
            };
            /** @description Budget created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetWithCategory"];
                };
            };
            /** @description Invalid budget payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    budget_summary: {
        parameters: {
            query?: {
                /** @description Year (default: current) */
                year?: number;
                /** @description Month 1-12 (default: current) */
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget vs actual summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSummaryResponse"];
                };
            };
            /** @description Invalid month parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_budget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Budget UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Budget not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_categories: {
        parameters: {
            query?: {
                /** @description Filter by 'income' or 'expense' */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            /** @description Invalid type filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_category: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Invalid category payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    list_ledger_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ledger transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_ledger_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLedgerTransactionRequest"];
            };
        };
        responses: {
            /** @description Ledger transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLedgerTransactionResponse"];
                };
            };
            /** @description Invalid ledger transaction payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idempotency key already used */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    migrate_single_to_double: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migration completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationResponse"];
                };
            };
        };
    };
    list_receipts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of receipts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_receipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveReceiptRequest"];
            };
        };
        responses: {
            /** @description Receipt saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid receipt payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    price_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    merge_products: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeProductsRequest"];
            };
        };
        responses: {
            /** @description Products merged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid product IDs */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Parsed receipt preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid QR data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reconcile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationUploadRequest"];
            };
        };
        responses: {
            /** @description Reconciliation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationUploadResponse"];
                };
            };
            /** @description Invalid upload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    category_breakdown: {
        parameters: {
            query?: {
                /** @description Start date (ISO). Default: first day of current month */
                start_date?: string;
                /** @description End date (ISO). Default: today */
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category spending breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryBreakdownResponse"];
                };
            };
            /** @description Invalid date range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monthly_report: {
        parameters: {
            query?: {
                /** @description Start year (default: 6 months ago) */
                start_year?: number;
                /** @description Start month 1-12 */
                start_month?: number;
                /** @description End year (default: current) */
                end_year?: number;
                /** @description End month 1-12 */
                end_month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly income/expense summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trends: {
        parameters: {
            query?: {
                /** @description Number of months (default 6, max 12) */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly trends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Invalid months parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_summary: {
        parameters: {
            query?: {
                /** @description Year to summarise (default: current) */
                year?: number;
                /** @description Month 1-12 (default: current) */
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Invalid month parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_transactions: {
        parameters: {
            query?: {
                /** @description Page size (default 50, max 200) */
                page_size?: number;
                /** @description Page offset (default 0) */
                page?: number;
                /** @description Filter by category UUID */
                category_id?: string;
                /** @description Filter by 'income' or 'expense' */
                type?: string;
                /** @description Filter by start date (inclusive) */
                start_date?: string;
                /** @description Filter by end date (inclusive) */
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Invalid filter parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Invalid transaction payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transaction UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transaction UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Invalid transaction payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Transaction UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is degraded or unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthError"];
                };
            };
        };
    };
    metrics_handler_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics in text format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
}
